### ISSUE TITLE
Higher crash rate with EXC_BAD_ACCESS since 6.2.1 -> 7.3.0 update of Sentry

### ISSUE THREAD

**Issue by cipherCOM** [getsentry/sentry-cocoa#1346]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-cocoa 7.3.0

### Steps to Reproduce

Since this is a mem crash and only happens for a fraction of our users I can't give clear instructions to reproduce this but rather only our config and the info that we updated from 6.2.1 to 7.3.0. Also the first time we have performance monitoring enabled.

```
options.dsn = "https://..."
options.environment = "AppStore"
options.attachStacktrace = true
options.add(inAppInclude: "InternalFramework")
options.sampleRate = NSNumber(value: 1.0)
options.tracesSampleRate = NSNumber(value: 1.0)
options.beforeSend = { event in
    ... e.g.
    event.tags = event.tags ?? [:]
    event.tags?[".device.model"] = UIDevice.current.model
    event.tags?[".network.status"] = AFNetworkReachabilityManager.shared().currentReachableNetwork
    ...
    var extra: [String: Any] = event.extra ?? [:]
    extra["log"] = log
    event.extra = extra
}
```

### Expected Result

No mem crashes

### Actual Result

Excerpts from our Sentry account:

```
OS Version: iOS 14.7.1 (18G82)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: BUS_NOOP at 0x003f836300000000
Crashed Thread: 14

Application Specific Information:
ersistRepairRecord: > setState: >
Attempted to dereference garbage pointer 0x3f836300000000.

Thread 14 Crashed:
0   CoreFoundation                  0x308ae55dc         CFDictionaryGetValue
1   Foundation                      0x30b288c90         [inlined] _NSSetLongLongValueAndNotify
2   Foundation                      0x30b288c90         _NSSetLongLongValueAndNotify
3   CFNetwork                       0x309ab2358         _CFNetworkHTTPConnectionCacheSetLimit
4   Foundation                      0x30b2b2f84         __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
5   Foundation                      0x30b1a0624         -[NSBlockOperation main]
6   Foundation                      0x30b2b53ac         __NSOPERATION_IS_INVOKING_MAIN__
7   Foundation                      0x30b1a02ac         -[NSOperation start]
8   Foundation                      0x30b2b5e50         __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
9   Foundation                      0x30b2b58dc         __NSOQSchedule_f
10  libdispatch.dylib               0x3084b1480         _dispatch_block_async_invoke2
11  libdispatch.dylib               0x3084a2818         _dispatch_client_callout
12  libdispatch.dylib               0x3084a5cf0         _dispatch_continuation_pop
13  libdispatch.dylib               0x3084a5380         _dispatch_async_redirect_invoke
14  libdispatch.dylib               0x3084b3fdc         _dispatch_root_queue_drain
15  libdispatch.dylib               0x3084b47d4         _dispatch_worker_thread2
16  libsystem_pthread.dylib         0x3a05a9764         _pthread_wqthread
```
```
OS Version: iOS 14.7.1 (18G82)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: BUS_NOOP at 0x003f836300000000
Crashed Thread: 18

Application Specific Information:
ingForObject: > setState: >
Attempted to dereference garbage pointer 0x3f836300000000.

Thread 18 Crashed:
0   CoreFoundation                  0x313c235dc         CFDictionaryGetValue
1   Foundation                      0x3163c6c90         [inlined] _NSSetLongLongValueAndNotify
2   Foundation                      0x3163c6c90         _NSSetLongLongValueAndNotify
3   CFNetwork                       0x314bf0358         _CFNetworkHTTPConnectionCacheSetLimit
4   Foundation                      0x3163f0f84         __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
5   Foundation                      0x3162de624         -[NSBlockOperation main]
6   Foundation                      0x3163f33ac         __NSOPERATION_IS_INVOKING_MAIN__
7   Foundation                      0x3162de2ac         -[NSOperation start]
8   Foundation                      0x3163f3e50         __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
9   Foundation                      0x3163f38dc         __NSOQSchedule_f
10  libdispatch.dylib               0x3135ef480         _dispatch_block_async_invoke2
11  libdispatch.dylib               0x3135e0818         _dispatch_client_callout
12  libdispatch.dylib               0x3135e3cf0         _dispatch_continuation_pop
13  libdispatch.dylib               0x3135e3380         _dispatch_async_redirect_invoke
14  libdispatch.dylib               0x3135f1fdc         _dispatch_root_queue_drain
15  libdispatch.dylib               0x3135f27d4         _dispatch_worker_thread2
16  libsystem_pthread.dylib         0x3a9ead764         _pthread_wqthread
```

### Additional Notes ###

I tried to do a basic white box code review of the differences between these to Sentry version to get an idea what happened. Tried to watch out for any special pitfalls that are a common cause for mem crashes (not copy retaining a block, not retaining an object, etc.).

I found some false positives because the getter is manually implemented (I think, these should not result in any bad ARC code, right?) like these, where I would propose to change them to `strong/retain`:

```
/sentry-cocoa-master/Sources/Sentry/include/SentryFramesTracker.h:
   17: @property (nonatomic, assign, readonly) SentryScreenFrames *currentFrames;
/sentry-cocoa-master/Sources/Sentry/Public/PrivateSentrySDKOnly.h:
   61: @property (class, nonatomic, assign, readonly) SentryScreenFrames *currentScreenFrames;
```

Another, I think, not problematic case where the compiler should choose `copy` automatically but then again would propose to explicitly add `copy`:

```
/sentry-cocoa-master/Sources/Sentry/Public/SentryOptions.h:
  191: @property (nullable, nonatomic) SentryTracesSamplerCallback tracesSampler;
```

But I also found one instance where a block isn't copied and this could lead to potential mem problems IMHO, but this only applies to the Tests so this can't be our reason.

```
/sentry-cocoa-master/Tests/SentryTests/Networking/NSURLProtocolSwizzle.h:
   11: @property (nullable, nonatomic, strong) ClassCallback registerCallback;
...
   13: @property (nullable, nonatomic, strong) ClassCallback unregisterCallback;
```

Any help or info would be appreciated 🙏

**Comment by philipphofmann** [comment]
Thanks, @cipherCOM, for opening up this detailed issue. After a quick glance at your stacktrace it seems like this could be related to https://github.com/getsentry/sentry-cocoa/issues/1328. A possible workaround is to disable auto HTTP request tracking like this 
```objc
[SentrySDK startWithConfigureOptions:^(SentryOptions *options) {
	NSMutableArray *integrations = [options.integrations mutableCopy];
	[integrations removeObject:@"SentryNetworkTrackingIntegration"];
	options.integrations = integrations;
}];
```

We are going add flags for easier disabling of the SentryNetworkTrackingIntegration soon, see https://github.com/getsentry/sentry-cocoa/issues/1327

**Comment by cipherCOM** [comment]
We planed to deploy `enableAutoPerformanceTracking = false` but we will reduce this to the above which only deactivates network tracking. Thanks for your swift response on this manner! We will report back if this improves the situation.

**Comment by rukano** [comment]
@philipphofmann we disabled this integration, nevertheless, we have now crashes on iOS 15 versions with the ViewControiller swizzling. We will disable the performance tracking for the moment. If you need more feedback to this issue, let us know, maybe we can provide further logs and stack traces.

![Sentry-Crash-iOS15](https://user-images.githubusercontent.com/97139/135282306-073dd078-6868-4b7b-835e-cc944ba0f7d5.png)

**Comment by philipphofmann** [comment]
@rukano, can you please open an extra issue for your problem. I think this is not related to this issue.

**Comment by philipphofmann** [comment]
It could be that we fixed the issue with https://github.com/getsentry/sentry-cocoa/pull/1354 in 7.4.1. Can you @cipherCOM please let us know if the fix works for you?

**Comment by philipphofmann** [comment]
Most likely, we fixed this with #1354. Would you please reopen the issue otherwise?

**Comment by philipphofmann** [comment]
Thanks for the update, @cipherCOM. I understand that you want to wait a bit until you enable performance tracking again. Fingers crossed, you don't have to reopen the issue in the future.

**Comment by ialimz** [comment]
Crash still exists in 7.5.1
Any idea?

<img width="290" alt="Screen Shot 2021-11-07 at 8 56 02 AM" src="https://user-images.githubusercontent.com/17988710/140633539-656159d5-4e54-4684-ac80-27d5bb5233a2.png">

```
OS Version: iOS 14.7.1 (18G82)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: BUS_NOOP at 0x003f836300000000
Crashed Thread: 9

Application Specific Information:
setState: > sIntentIdentifier >
Attempted to dereference garbage pointer 0x3f836300000000.

Thread 9 Crashed:
0   CoreFoundation                  0x319c1b5dc         CFDictionaryGetValue
1   Foundation                      0x31c3bec94         [inlined] <redacted>
2   Foundation                      0x31c3bec94         <redacted>
3   CFNetwork                       0x31abe835c         _CFNetworkHTTPConnectionCacheSetLimit
4   Foundation                      0x31c3e8f88         <redacted>
5   Foundation                      0x31c2d6628         <redacted>
6   Foundation                      0x31c3eb3b0         <redacted>
7   Foundation                      0x31c2d62b0         <redacted>
8   Foundation                      0x31c3ebe54         <redacted>
9   Foundation                      0x31c3eb8e0         <redacted>
10  libdispatch.dylib               0x3195e7484         <redacted>
11  libdispatch.dylib               0x3195d881c         <redacted>
12  libdispatch.dylib               0x3195e0004         <redacted>
13  libdispatch.dylib               0x3195e0c00         <redacted>
14  libdispatch.dylib               0x3195eb4bc         <redacted>
15  libsystem_pthread.dylib         0x3b17d97a4         _pthread_wqthread

Thread 0
0   libsystem_kernel.dylib          0x37627e4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x37627d884         mach_msg
2   CoreFoundation                  0x319c52e58         <redacted>
3   CoreFoundation                  0x319c4ccf8         <redacted>
4   CoreFoundation                  0x319c4c308         CFRunLoopRunSpecific
5   GraphicsServices                0x3489eb734         GSEventRunModal
6   UIKitCore                       0x31e61a75c         <redacted>
7   UIKitCore                       0x31e61ffcc         UIApplicationMain
8   Divar                           0x2020f28b4         main (main.swift:16)
9   libdyld.dylib                   0x31965fcf8         <redacted>

Thread 1 name: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib          0x37627e4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x37627d884         mach_msg
2   CoreFoundation                  0x319c52e58         <redacted>
3   CoreFoundation                  0x319c4ccf8         <redacted>
4   CoreFoundation                  0x319c4c308         CFRunLoopRunSpecific
5   Foundation                      0x31c2bed8c         <redacted>
6   Foundation                      0x31c2bec58         <redacted>
7   UIKitCore                       0x31e6cf304         <redacted>
8   Foundation                      0x31c43030c         <redacted>
9   libsystem_pthread.dylib         0x3b17d7bfc         _pthread_start

Thread 2 name: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x37627e4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x37627d884         mach_msg
2   CoreFoundation                  0x319c52e58         <redacted>
3   CoreFoundation                  0x319c4ccf8         <redacted>
4   CoreFoundation                  0x319c4c308         CFRunLoopRunSpecific
5   CFNetwork                       0x31ac59b38         _CFURLStorageSessionCopyCache
6   Foundation                      0x31c43030c         <redacted>
7   libsystem_pthread.dylib         0x3b17d7bfc         _pthread_start

Thread 3
0   libsystem_kernel.dylib          0x3762a3734         __semwait_signal
1   libsystem_c.dylib               0x32c516a14         nanosleep
2   libsystem_c.dylib               0x32c5167f8         sleep
3   Divar                           0x20375428c         monitorCachedData
4   libsystem_pthread.dylib         0x3b17d7bfc         _pthread_start

Thread 4 name: SentryCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib          0x37627e4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x37627d884         mach_msg
2   Divar                           0x20374f8cc         handleExceptions
3   libsystem_pthread.dylib         0x3b17d7bfc         _pthread_start

Thread 6 name: com.apple.CFStream.LegacyThread
0   libsystem_kernel.dylib          0x37627e4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x37627d884         mach_msg
2   CoreFoundation                  0x319c52e58         <redacted>
3   CoreFoundation                  0x319c4ccf8         <redacted>
4   CoreFoundation                  0x319c4c308         CFRunLoopRunSpecific
5   CoreFoundation                  0x319c70b1c         <redacted>
6   libsystem_pthread.dylib         0x3b17d7bfc         _pthread_start

Thread 7 name: com.apple.CFSocket.private
0   libsystem_kernel.dylib          0x3762a362c         select$DARWIN_EXTSN
1   CoreFoundation                  0x319c60034         <redacted>
2   libsystem_pthread.dylib         0x3b17d7bfc         _pthread_start

Thread 8 name: AVAudioSession Notify Thread
0   libsystem_kernel.dylib          0x37627e4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x37627d884         mach_msg
2   CoreFoundation                  0x319c52e58         <redacted>
3   CoreFoundation                  0x319c4ccf8         <redacted>
4   CoreFoundation                  0x319c4c308         CFRunLoopRunSpecific
5   AudioSession                    0x32923af20         <redacted>
6   AudioSession                    0x32923d0d8         <redacted>
7   libsystem_pthread.dylib         0x3b17d7bfc         _pthread_start

Thread 9 Crashed:
0   CoreFoundation                  0x319c1b5dc         CFDictionaryGetValue
1   Foundation                      0x31c3bec94         [inlined] <redacted>
2   Foundation                      0x31c3bec94         <redacted>
3   CFNetwork                       0x31abe835c         _CFNetworkHTTPConnectionCacheSetLimit
4   Foundation                      0x31c3e8f88         <redacted>
5   Foundation                      0x31c2d6628         <redacted>
6   Foundation                      0x31c3eb3b0         <redacted>
7   Foundation                      0x31c2d62b0         <redacted>
8   Foundation                      0x31c3ebe54         <redacted>
9   Foundation                      0x31c3eb8e0         <redacted>
10  libdispatch.dylib               0x3195e7484         <redacted>
11  libdispatch.dylib               0x3195d881c         <redacted>
12  libdispatch.dylib               0x3195e0004         <redacted>
13  libdispatch.dylib               0x3195e0c00         <redacted>
14  libdispatch.dylib               0x3195eb4bc         <redacted>
15  libsystem_pthread.dylib         0x3b17d97a4         _pthread_wqthread

Thread 10
0   libsystem_kernel.dylib          0x3762a40a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b17d97f0         _pthread_wqthread

Thread 11
0   libobjc.A.dylib                 0x3433c8240         objc_msgSend
1   Foundation                      0x31c3005b8         <redacted>
2   Divar                           0x20375e168         encodeObject
3   Divar                           0x20375e7c4         encodeObject
4   Divar                           0x20375dffc         +[SentryCrashJSONCodec encode:options:error:]
5   Divar                           0x20372219c         -[SentryCrashScopeObserver toJSONEncodedCString:]
6   Divar                           0x203721f58         -[SentryCrashScopeObserver addBreadcrumb:]
7   Divar                           0x20373a814         -[SentryScope addBreadcrumb:]
8   Divar                           0x20372d948         -[SentryHub addBreadcrumb:]
9   Divar                           0x203739888         +[SentrySDK addBreadcrumb:]
10  Divar                           0x203731fe0         -[SentryNetworkTracker observeValueForKeyPath:ofObject:change:context:]
11  Foundation                      0x31c3c1e1c         <redacted>
12  Foundation                      0x31c3c4394         <redacted>
13  Foundation                      0x31c3c3e00         <redacted>
14  Foundation                      0x31c2fd0e0         <redacted>
15  Foundation                      0x31c3bed70         <redacted>
16  CFNetwork                       0x31aa13f20         <redacted>
17  CFNetwork                       0x31aa13b2c         <redacted>
18  CFNetwork                       0x31aab8e90         CFURLDownloadCancel
19  CFNetwork                       0x31aa1968c         <redacted>
20  libdispatch.dylib               0x3195e7484         <redacted>
21  libdispatch.dylib               0x3195d881c         <redacted>
22  libdispatch.dylib               0x3195e0004         <redacted>
23  libdispatch.dylib               0x3195e0c34         <redacted>
24  libdispatch.dylib               0x3195eb4bc         <redacted>
25  libsystem_pthread.dylib         0x3b17d97a4         _pthread_wqthread

Thread 12
0   libsystem_kernel.dylib          0x3762a40a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b17d97f0         _pthread_wqthread

Thread 13
0   RunningBoardServices            0x32c5db0c4         <redacted>
1   RunningBoardServices            0x32c5bd998         <redacted>
2   RunningBoardServices            0x32c5ba758         <redacted>
3   CFNetwork                       0x31aa7ca88         CFURLProtectionSpaceGetServerTrust
4   CFNetwork                       0x31aa86a34         CFHTTPCookieCopyPath
5   libdispatch.dylib               0x3195e7484         <redacted>
6   libdispatch.dylib               0x3195d881c         <redacted>
7   libdispatch.dylib               0x3195e0004         <redacted>
8   libdispatch.dylib               0x3195e0c34         <redacted>
9   libdispatch.dylib               0x3195eb4bc         <redacted>
10  libsystem_pthread.dylib         0x3b17d97a4         _pthread_wqthread

Thread 14
0   libsystem_kernel.dylib          0x3762a40a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b17d97f0         _pthread_wqthread



EOF
```

**Comment by EdgarDegas** [comment]
@ialimz Which version were you using before 7.5.1?

**Comment by ialimz** [comment]
@philipphofmann 7.3.0

**Comment by bruno-garcia** [comment]
I believe it might be a dupe but reopening so @philipphofmann @brustolin can double check

**Comment by philipphofmann** [comment]
This is the same issue as https://github.com/getsentry/sentry-cocoa/issues/1448. I'm going to close this.
