### ISSUE TITLE
Crash in monitorCachedData

### ISSUE THREAD

**Issue by stefanfuerst** [getsentry/sentry-cocoa#1650]
### Platform

macOS

### Installed

Manually

### Version

7.8

### Steps to Reproduce

Lately I'm often getting C++ Exception: _NSCoreDataException that look like this

```
libsystem_kernel    0x1bdbf4ebc  __semwait_signal
libsystem_c         0x1bdaffd84  nanosleep
libsystem_c         0x1bdb0a6e8  sleep
Sentry              0x1010a9384  monitorCachedData (Sources/SentryCrash/Recording/SentryCrashCachedData.c:139)
libsystem_pthread   0x1bdc2d23c  _pthread_start
```

I can't tell if this is not parsed properly or an issue with Sentry. Also I was not able to reproduce this locally.

### Expected Result

Display of details of the _NSCoreDataException

### Actual Result

Just C++ Exception: _NSCoreDataException

**Comment by stefanfuerst** [comment]
I did some experiments by creating an exception on my own

This ends up in Sentry as **C++ Exception: _NSCoreDataException** without stack trace
```
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification
{
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(4 * NSEC_PER_SEC)), dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [[NSClassFromString(@"_NSCoreDataException") exceptionWithName:@"Oh Damn" reason:@"Crash to crash" userInfo:nil] raise];
    });
}
```
While generating a regular Exception is reported with the correct parameters and stack trace

```
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification
{
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(4 * NSEC_PER_SEC)), dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [NSException exceptionWithName:@"Oh Damn" reason:@"Crash to crash" userInfo:nil] raise];
    });
}

```
I did not yet figure out the point where reporting goes wrong

**Comment by brustolin** [comment]
Hey @stefanfuerst, thanks for letting us know this.
I will take a look.

**Comment by philipphofmann** [comment]
@brustolin was able to reproduce this. We can't give you an ETA for fixing this, though @stefanfuerst.

**Comment by philipphofmann** [comment]
We see rare occurrences of this in our [internal SDK crashes](https://sentry.sentry.io/issues/?project=4505469596663808&query=is%3Aunresolved+monitorCachedData&referrer=issue-list&sort=user&statsPeriod=14d).

**Comment by grzegorzkrukowski** [comment]
Is there any update on this one ? it keeps happening in our Application on the latest version still

**Comment by brustolin** [comment]
Sorry @grzegorzkrukowski, no updates on this one yet.

**Comment by rickarddahlvolvocars** [comment]
Any updates on this?

We get this crash rarely, so far only for one user, 5 crashes.
It happens on iOS 16.6.1
We user Sentry SPM with version 8.38.

```
          Thread
0  libsystem_kernel.dylib         0x14ac __semwait_signal + 8
1  libsystem_c.dylib              0x541c nanosleep + 216
2  libsystem_c.dylib              0x16058 sleep + 48
3  **<OUR APP NAME>**                     0x6dcae88 monitorCachedData + 660
4  libsystem_pthread.dylib        0x30ec _pthread_start + 116
5  libsystem_pthread.dylib        0x172c thread_start + 8
```

and

```
          SentryCrash Exception Handler (Secondary)
0  libsystem_kernel.dylib         0x1030 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x12b18 mach_msg2_internal + 76
2  libsystem_kernel.dylib         0x12db8 mach_msg_overwrite + 484
3  libsystem_kernel.dylib         0x1524 mach_msg + 20
4  **<OUR APP NAME>**                     0x6db137c handleExceptions + 172
5  libsystem_pthread.dylib        0x30ec _pthread_start + 116
6  libsystem_pthread.dylib        0x172c thread_start + 8
        
```

**Comment by philipphofmann** [comment]
@rickarddahlvolvocars, I'm sorry, but we haven't gotten to this yet. Thanks for the details.

**Comment by kahest** [comment]
this seems to be an [unsolved issue in KSCrash](https://github.com/kstenerud/KSCrash/issues/444). we see a low volume of events for this crash in our [internal monitoring](https://sentry.sentry.io/discover/homepage/?dataset=errors&field=title&field=project&field=user.display&field=sdk.name&field=sdk.version&field=count%28%29&name=All%20Errors&project=4505469596663808&query=stack.function%3A%2AmonitorCachedData%2A&queryDataset=error-events&sort=-count&statsPeriod=90d&yAxis=count%28%29)

**Comment by sindresorhus** [comment]
I'm seeing this too, with Sentry 9.1.0.

```
EXC_BAD_ACCESS: @Ѐd
 >
Attempted to dereference null pointer.

  libsystem_kernel    0x193f9e2f4  __semwait_signal
  libsystem_c         0x193e7febc  sleep
  Dato                0x1045b059c  monitorCachedData
  libsystem_pthread   0x193fddc04  _pthread_start
```

Another stack trace:

```
EXC_BAD_ACCESS: Exception 1, Code 1, Subcode 0 >
Attempted to dereference null pointer.

  libsystem_kernel    0x19714e2f4  __semwait_signal
  libsystem_c         0x19702febc  sleep
  Dato                0x104a1459c  monitorCachedData
  libsystem_pthread   0x19718dc04  _pthread_start
```

According to the user, my app just crashed randomly.

https://sindresorhus.sentry.io/issues/7235639252/events/fcd0e375f0c14362aa844abc3fec7326/

https://sindresorhus.sentry.io/issues/6946835991/events/e13adb8dddd54f66a34e03e13165653f/

https://sindresorhus.sentry.io/issues/6543931134/events/4d3b0d5e81a243f2947e1e9c7f6b8d1f/

**Comment by denrase** [comment]
For the `monitorCachedData` stack trace, I assumed that the issue may be in updateThreadList() in SentryCrashCachedData.c, where the background thread frees cached thread data while the crash handler is still reading it.

The code also mentions that there are potential races, and we have disabled thread sanitizer with `SENTRY_DISABLE_THREAD_SANITIZER("Known data race to fix")`.

I tried to provoke the crash with a unit test, but I could not reliably reproduce this crash, even with aggressive stress testing. Did managed to trigger one crash with a similar signature, but it wasn't consistently reproducible.

Looking upstream, KSCrash has updated this part of their code-base to have fixed this exact issue in [PR #733](https://github.com/kstenerud/KSCrash/pull/733):

> **Refactor KSThreadCache to use atomic exchange pattern**
> - Replace fragile semaphore-based synchronization with lock-free atomics
> - Use atomic exchange pattern for thread safety
> - Consolidate thread data into single struct
> - Background thread skips update when cache is acquired by crash handler

They explicitly called the semaphore-based approach (which we also use) "fragile" and replaced it with atomic pointers and a double-buffer pattern.

Maybe it's worth adopting KSCrash's fix as well here, WDYT?

**Comment by philippsuess** [comment]
> Maybe it's worth adopting KSCrash's fix as well here, WDYT?

@denrase, yes, please.

**Comment by denrase** [comment]
I think we have two separate issues here. One being mis-identification of NSException subclasses as C++ exceptions, and the other being potential crashes/issues in monitorCachedData itself.

**Comment by denrase** [comment]
- NSException sub-classes being reported as C++ is fixed by #7420
- Crashes due to data races are fixed by #7423 

I hope that these fixed all other reports that were collected in here. Thx all for reporting these! 🙇

**Comment by sindresorhus** [comment]
@denrase I'm still seeing `monitorThreadCache` crashes in Sentry Cocoa 9.11.0

```
EXC_BAD_ACCESS: placeCharactersInRange:withString: >
Attempted to dereference null pointer.

  libsystem_kernel    0x18e2a02f4  __semwait_signal
  libsystem_c         0x18e181ebc  sleep
  Supercharge         0x103526798  monitorThreadCache
  libsystem_pthread   0x18e2dfc04  _pthread_start
```

https://sindresorhus.sentry.io/share/issue/494e4114e6244bd68b0a94c87178095a/

**Comment by denrase** [comment]
@sindresorhus Thank you, i will take a look.

**Comment by denrase** [comment]
@sindresorhus Thanks for the event data. This does not look like `monitorThreadCache` itself is crashing. In the processed event, the `monitorThreadCache` thread is marked `crashed: false` and is just sleeping.

The exception points to `thread_id: 0`, but thread 0 / the main thread is missing from `threads.values`, and no thread is marked `crashed: true`. Because the real crashed thread was not present after conversion, Sentry likely fell back to the first remaining in-app stacktrace, which happens to be our SentryCrash `monitorThreadCache` helper thread.

The actual crash appears to be an app/main-thread EXC_BAD_ACCESS null dereference, with placeCharactersInRange:withString: as the only remaining clue, likely from AppKit/text input handling.

We need to find out why there were no stacktraces for the crashed (main) thread, which lead to it being dropped from the event.

**Comment by sindresorhus** [comment]
Another example: https://sindresorhus.sentry.io/share/issue/d257c55f3cbd409b88b38f24242371a5/

**Comment by denrase** [comment]
@sindresorhus We released a [fix](https://github.com/getsentry/sentry-cocoa/pull/7866) for missing crashed threads, which is **very** similar in shape to your reported issue. It's in release [9.12.1](https://github.com/getsentry/sentry-cocoa/releases/tag/9.12.1).

**Comment by philprime** [comment]
Closing — this was fixed by #7423 (merged Feb 2026), which replaced the semaphore-based synchronization with lock-free atomic exchange in `SentryCrashCachedData.c`. The crash-causing pattern (individual pointer swaps with `usleep(1)` sync) no longer exists.

**EDIT: I'll keep this open for a couple more days.**

**Comment by denrase** [comment]
Closing this for now. Please feel free to re-open if this is still an issue.
