### ISSUE TITLE
400 Error When Sending Events

### ISSUE THREAD

**Issue by giilby** [getsentry/sentry-cocoa#256]
_Platform:_
- [x]  iOS
- [ ]  tvOS
- [ ]  MacOS
- [ ]  watchOS

_Swift:_
- [x]  Yes -> If yes, which version?  4.1
- [ ]  No

_sentry-cocoa installed with:_
- [x] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**4.0.1**

---
I have following issue:

None of my messages or crash reports are being successfully sent to Sentry's servers. Instead, the Sentry client is receiving this error message:

"Bad data decoding request (UnicodeDecodeError, 'utf8' codec can't decode byte 0xa3 in position 1: invalid start byte)"

I have also tried version 3.13.1 and 3.9.1 of sentry-cocoa, and the same issue occurs.

Here's the full response:

```
<NSHTTPURLResponse: 0x60c000227f00> { URL: https://sentry.io/api/[id]/store/ } { Status Code: 400, Headers {
    "Cache-Control" =     (
        "max-age=0"
    );
    Connection =     (
        "keep-alive"
    );
    "Content-Language" =     (
        en
    );
    "Content-Length" =     (
        129
    );
    "Content-Type" =     (
        "application/json"
    );
    Date =     (
        "Fri, 27 Jul 2018 22:42:05 GMT"
    );
    Expires =     (
        "Fri, 27 Jul 2018 22:42:05 GMT"
    );
    "Last-Modified" =     (
        "Fri, 27 Jul 2018 22:42:05 GMT"
    );
    Server =     (
        nginx
    );
    "Strict-Transport-Security" =     (
        "max-age=31536000; includeSubDomains; preload"
    );
    Vary =     (
        "Accept-Language, Cookie"
    );
    "X-Content-Type-Options" =     (
        nosniff
    );
    "X-Frame-Options" =     (
        deny
    );
    "X-Sentry-Error" =     (
        "Bad data decoding request (UnicodeDecodeError, 'utf8' codec can't decode byte 0xa3 in position 1: invalid start byte)"
    );
    "X-Served-By" =     (
        "web-ee8f0660"
    );
    "X-XSS-Protection" =     (
        "1; mode=block"
    );
} }
```

**Steps to reproduce:**
- Attempt to send an event (a very simple one with a short alphanumeric message) or capture a crash

**Actual result:**
- Event is not sent to Sentry due to a 400 error (observed in `SentryRequestOperation`)

**Expected result:**
- Event is successfully sent to Sentry

**Comment by HazAT** [comment]
Hey, I just tried it and works normally.
Can you enable verbose logging and check what the log says?

**Comment by giilby** [comment]
Strange...it's working for me now, and I didn't change anything other than enabling verbose logging. Maybe this was a temporary server-side issue?

**Comment by jan-auer** [comment]
Yes, the problem was resolved shortly after you opened this issue. Sorry for the inconvenience!

**Comment by iDevPro** [comment]
I have this issue too, but not fixed yet :(
Sentry 9.1.2
Client 4.4.3 (CocoaPods)
