### ISSUE TITLE
SwiftUI preview crash: Sentry does not contain a slice for arm64e-apple-macosx21.1

### ISSUE THREAD

**Issue by DominikPalo** [getsentry/sentry-cocoa#4350]
```[tasklist]
### 🛑 Blocked by
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3398
``` 
---

### Platform

macOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.36.0

### Xcode Version

16.0 (16A242d)

### Did it work on previous versions?

Yes (Xcode 15)

### Steps to Reproduce

We have a macOS SwiftUI app that references the Sentry framework. Since I updated Xcode to 16.0, the SwiftUI preview has stopped working. When I open any SwiftUI view file containing a PreviewProvider implementation, the Xcode preview window crashes. However, we can build and run the app without any issues.

### Expected Result

SwiftUI preview window shows a mocked preview of the opened view.

### Actual Result

SwiftUI preview fails with the `Sentry does not contain a slice for arm64e-apple-macosx21.1` error:

![Image](https://github.com/user-attachments/assets/9722a994-9384-4b48-aa63-78ab8acebded)
```
== PREVIEW UPDATE ERROR:

    FailedToLaunchAppError: Failed to launch com.slido.SlidoApp
    
    /Users/dpalo/Library/Developer/Xcode/DerivedData/SlidoAddin-fddfekbcupxqcceaxbdflfzoaani/Build/Products/Debug/Slido.app
    
    ==================================
    
    |  [Remote] JITError
    |  
    |  ==================================
    |  
    |  |  [Remote] LLVMError
    |  |  
    |  |  LLVMError: LLVMError(description: "Universal binary /Users/dpalo/Library/Developer/Xcode/DerivedData/SlidoAddin-fddfekbcupxqcceaxbdflfzoaani/Build/Products/Debug/Sentry.framework/Sentry does not contain a slice for arm64e-apple-macosx21.1")
```

**Comment by brustolin** [comment]
Hello @DominikPalo, thanks for reaching out, I was able to reproduce the problem, we will investigate a solution for it.

**Comment by brustolin** [comment]
We need to build our framework with Xcode 16 to use the standard architectures, which includes arm64e now.
We plan to make a new release next week.

Im so sorry about the inconvenience.

**Comment by brustolin** [comment]
This is blocked by https://github.com/getsentry/sentry-cocoa/pull/3398

**Comment by tonyarnold** [comment]
I am seeing this in my project too. Good to hear that work is underway to fix the underlying issue.

**Comment by brustolin** [comment]
This was solved in #3396, and will be available in the next release.

**Comment by kushsolitary** [comment]
> This was solved in [#3398](https://github.com/getsentry/sentry-cocoa/pull/3398), and will be available in the next release.

Hi, even on the latest commit, I am facing the same issue. I've tried clearing derived data and cache but the issue persists.

**Comment by brustolin** [comment]
Hello @kushsolitary, did you tried direct from main? 
Because we did not released a version with fix yet.

**Comment by kushsolitary** [comment]
> Hello [@kushsolitary](https://github.com/kushsolitary), did you tried direct from main? Because we did not released a version with fix yet.

Yes, it's on the main branch and preview is crashing with the same error: `Sentry.framework/Sentry does not contain a slice for arm64e-apple-macosx21.1`

**Comment by brustolin** [comment]
Ow, my bad, it won't work using main, because main points to the latest release binary.
We really need to make a new release. Sorry about the trouble.
We're probably making a new release today.

**Comment by kushsolitary** [comment]
> Ow, my bad, it won't work using main, because main points to the latest released binary. We really need to make a new release. Sorry about the trouble. We're probably making a new release today.

No worries, thanks for the update.

**Comment by tonyarnold** [comment]
Did this go out with 8.37.0? I just updated, and my previews are still broken: 

```
Universal binary /Users/tonyarnold/Library/Developer/Xcode/DerivedData/Reveal-bfyimdvyberhixdfsrrbidcdmyuz/Build/Products/Debug/Sentry.framework/Sentry does not contain a slice for arm64e-apple-macosx21.1
```

**Comment by kushsolitary** [comment]
The release notes don't mention this PR so it looks like it isn't included 😦

**Comment by tonyarnold** [comment]
What kind of release schedule is Sentry on? This is a pretty critical issue.

**Comment by kushsolitary** [comment]
@brustolin any ETA on when will this be released? It's really hampering our development speed.

**Comment by brustolin** [comment]
Hello, @kushsolitary  and @tonyarnold.

Our release process is twofold, designed to prevent releasing bugs as much as possible. Yesterday, we promoted the latest beta version to release, and today we will release the unreleased features as a Beta so we can test them in real apps. Users can also try them, knowing it is a beta version.

I we will have it in the next few hours. I will let you know in here.

**Comment by brustolin** [comment]
[8.38.0-beta.1](https://github.com/getsentry/sentry-cocoa/releases/tag/8.38.0-beta.1) was released.

You need to use the exact version in Xcode

![Image](https://github.com/user-attachments/assets/2f1cbced-d699-4e30-abb7-1ad4badc5407)

**Comment by tonyarnold** [comment]
Thanks @indragiek for me as well — I see you there, buddy 😂

**Comment by DominikPalo** [comment]
@brustolin & @indragiek thank you guys! I've just updated our project to `8.38.0-beta.1` and I can confirm that the SwiftUI preview works as expected 👍
