### ISSUE TITLE
Unable to build with Xcode 26 for visionOS

### ISSUE THREAD

**Issue by levinli303** [getsentry/sentry-cocoa#5667]
### Platform

visionOS

### Environment

Other

### Installed

Swift Package Manager

### Version

8.53.2

### Xcode Version

26.0 beta 3

### Did it work on previous versions?

16.4

### Steps to Reproduce

1. create an Xcode project with iOS target and add visionOS support
2. add code that starts Sentry
3. build the project

### Expected Result

Should build fine

### Actual Result

The build fails in `Compiling Swift module Sentry`

```
<unknown>:0: error: C99 was enabled in PCH file but is currently disabled
<unknown>:0: error: module file /Users/[redacted]/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/SwiftShims-8E9KY877QCTXDJCE0XIKBPGI7.pcm cannot be loaded due to a configuration mismatch with the current compilation
<unknown>:0: error: missing required module 'SwiftShims'
```

**Comment by philippsuess** [comment]
I just tried compiling a sample project including sentry-cocoa 8.53.2 via SPM on Xcode 26 beta 3 and it worked.

You can often resolve errors with `SwiftShims` by doing a clean build or clearing the `~/Library/Developer/Xcode/DerivedData` folder. Please let us know if that works.

**Comment by vedlai** [comment]
I have the same issue, 8.53.2, Xcode 26, Tahoe,  Swift 6. Cleaned Derived Data and Clean Build.

This might be of help, seems similar environment.

https://github.com/firebase/firebase-ios-sdk/issues/14950

**Comment by philippsuess** [comment]
@vedlai, thanks for the hint. I tried using Sentry-Cocoa 8.53.2 with Xcode 26 beta.3 and Swift 6 on macOS 15.5, and was unable to reproduce the issue. It could be related to macOS Tahoe. Could you maybe provide us with a small sample app, so we can reproduce it?

**Comment by vedlai** [comment]
@philipphofmann I think it is Tahoe and I think it is any visionOS app. I started a blank app and got the same error.

I think it is related to Tahoe because the Firebase example was Tahoe as well.

It seems to be isolated to Sentry and not Sentry SwiftUI. 

Clarification: Sentry SwiftUI does not work either but I think it is because Sentry doesn't work.

**Comment by philippsuess** [comment]
> I started a blank app and got the same error.

@vedlai, do you mean a blank app with or without Sentry?

**Comment by vedlai** [comment]
@philipphofmann Adding Sentry

So a brand new visionOS project on Tahoe and Xcode Beta then just add Sentry with SPM.

**Comment by levinli303** [comment]
I'm on Sequoia so probably not related to being on Tahoe.

**Comment by philprime** [comment]
Probably related to #5435

**Comment by vedlai** [comment]
@philprime plausible but it only happens on visionOS so I believe only arm64. 

Just made a new Multiplatform project that includes macOS and iOS and those 2 platforms build fine.

@philipphofmann I found this extra information

```
SwiftExplicitDependencyCompileModuleFromInterface arm64 /Users/<user-folder>/Library/Developer/Xcode/DerivedData/SentryTest-flsvjxbwleqdnsaymtsydicicxcg/Build/Intermediates.noindex/SwiftExplicitPrecompiledModules/Sentry-31HNN5GL4VE6H.swiftmodule

<unknown>:0: error: C99 was enabled in PCH file but is currently disabled
<unknown>:0: error: module file /Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/SwiftShims-20LFEXT1YJTYIH99SZ1RI943.pcm cannot be loaded due to a configuration mismatch with the current compilation
<unknown>:0: error: missing required module 'SwiftShims'
Failed frontend command:
/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -compile-module-from-interface -target arm64-apple-xros1.0 -clang-target arm64-apple-xros26.0 -target-sdk-name xros26.0 -target-sdk-version 26.0 -swift-version 5 -sdk /Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/SDKs/XROS26.0.sdk -suppress-warnings -disable-objc-attr-requires-foundation-module -enable-ossa-modules -validate-clang-modules-once -clang-build-session-file /Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -track-system-dependencies -Xcc -fno-color-diagnostics -Xcc -D_LIBCPP_HARDENING_MODE\=_LIBCPP_HARDENING_MODE_DEBUG -Xcc -ivfsstatcache -Xcc /Users/<user-folder>/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/xros26.0-23M5290e-3885c01c3e6b6a337905948deab2002e603cd0391b57a4f7518316cfd3bb2c7c.sdkstatcache -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -disable-clang-spi /Users/<user-folder>/Library/Developer/Xcode/DerivedData/SentryTest-flsvjxbwleqdnsaymtsydicicxcg/Build/Products/Debug-xros/Sentry.framework/Modules/Sentry.swiftmodule/arm64-apple-xros.private.swiftinterface -module-name Sentry -target arm64-apple-xros1.0 -enable-objc-interop -cxx-interoperability-mode\=default -enable-library-evolution -swift-version 5 -enforce-exclusivity\=checked -O -module-name Sentry -enable-bare-slash-regex -explicit-interface-module-build -disable-implicit-swift-modules -Xcc -fno-implicit-modules -Xcc -fno-implicit-module-maps -swift-module-file\=Accessibility\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/Accessibility.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=Accessibility\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Accessibility-CL4RHU1EEBQZQEEXRQHBZ4GBL.pcm -Xcc -fmodule-file\=CFNetwork\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/CFNetwork-47ABVRXJIREJ66J7NA4WJPHQY.pcm -swift-module-file\=Combine\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/Combine.swiftmodule/arm64e-apple-xros.swiftmodule -swift-module-file\=CoreFoundation\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/CoreFoundation.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=CoreFoundation\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/CoreFoundation-2R2YGZ19CH7JC5NTPWY3SCO6O.pcm -swift-module-file\=CoreGraphics\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/CoreGraphics.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=CoreGraphics\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/CoreGraphics-5TQ2ZMTSKPDI0AL37XRLGDGRI.pcm -swift-module-file\=CoreImage\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/CoreImage.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=CoreImage\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/CoreImage-4Q7OGVQ1OA0CKUHGTH9PDYT4Q.pcm -swift-module-file\=CoreText\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/CoreText.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=CoreText\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/CoreText-8OO60UPS0LZML4WFAV12BUD8W.pcm -swift-module-file\=CoreTransferable\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/CoreTransferable.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=CoreTransferable\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/CoreTransferable-76JWTPS0SREASR981DHLPHYQB.pcm -swift-module-file\=CoreVideo\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/CoreVideo.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=CoreVideo\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/CoreVideo-63N3P67G2ZYCS3QPC27GNV1MZ.pcm -swift-module-file\=Darwin\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/Darwin.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=Darwin\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Darwin-3LJQEZZ7I4AROQ4WQUY6GY844.pcm -swift-module-file\=DataDetection\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/DataDetection.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=DataDetection\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/DataDetection-8ASIGOLRDZRNWU1HSM93YIUQ1.pcm -swift-module-file\=DeveloperToolsSupport\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/DeveloperToolsSupport.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=DeveloperToolsSupport\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/DeveloperToolsSupport-2QKUVJLF9D29AQQB2PTDK655R.pcm -swift-module-file\=Dispatch\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/Dispatch.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=Dispatch\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Dispatch-6IOE6RXZ6P0Y4MPA0CYV087OY.pcm -swift-module-file\=FileProvider\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/FileProvider.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=FileProvider\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/FileProvider-ACI4VL3EF8E2HHEXTFP30N0S4.pcm -swift-module-file\=Foundation\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/Foundation.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=Foundation\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Foundation-7VXOBEKW0VX0ZMHQ55LWTO0W2.pcm -Xcc -fmodule-file\=IOSurface\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/IOSurface-AX3L7R1AEGZDSSISHWF12L4I0.pcm -Xcc -fmodule-file\=ImageIO\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/ImageIO-2DMTL56SF52JL150EEYELOYN.pcm -Xcc -fmodule-file\=MachO\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/MachO-ETK63LOM1GJSKTIOTVMYABMG2.pcm -swift-module-file\=Metal\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/Metal.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=Metal\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Metal-WZ9A3ZG48K34RUEZIAV4AB5A.pcm -swift-module-file\=OSLog\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/OSLog.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=OSLog\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/OSLog-2AIUDAKVRYW4W8FF4NPK9OKRM.pcm -swift-module-file\=ObjectiveC\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/ObjectiveC.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=ObjectiveC\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/ObjectiveC-BWW9UFPKE12MZ9WJGNQ1NR1FQ.pcm -swift-module-file\=Observation\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/Observation.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=OpenGLES\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/OpenGLES-477GYI828XGJZPLS09XEFYVMG.pcm -swift-module-file\=QuartzCore\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/QuartzCore.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=QuartzCore\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/QuartzCore-FD898VD9M33QB3VMT3Y94RVU.pcm -Xcc -fmodule-file\=Security\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Security-2ELT7VG5GTZGE38PSFKL2TRXA.pcm -Xcc -fmodule-file\=Sentry\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/SentryTest-flsvjxbwleqdnsaymtsydicicxcg/Build/Intermediates.noindex/SwiftExplicitPrecompiledModules/Sentry-CRZRLHROC42J8LRJWKPP8RJP6.pcm -swift-module-file\=Spatial\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/Spatial.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=Spatial\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Spatial-4MEXJIHYOOB4GPS62VFO0HKNN.pcm -swift-module-file\=Swift\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/Swift.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=SwiftShims\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/SwiftShims-20LFEXT1YJTYIH99SZ1RI943.pcm -swift-module-file\=SwiftUICore\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/SwiftUICore.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=SwiftUICore\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/SwiftUICore-660JS4MF0Q28O57ACBRU3887J.pcm -swift-module-file\=Symbols\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/Symbols.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=Symbols\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Symbols-1AKWZ7UO9OY9M6XHTUQE4ZU8S.pcm -swift-module-file\=System\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/System.swiftmodule/arm64e-apple-xros.swiftmodule -swift-module-file\=UIKit\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/UIKit.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=UIKit\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/UIKit-2MHUD4UIUTJ5900WLWSZIS0S9.pcm -Xcc -fmodule-file\=UIUtilities\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/UIUtilities-7JUXW00L8URLH2T1B9BFDAG80.pcm -swift-module-file\=UniformTypeIdentifiers\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/UniformTypeIdentifiers.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=UniformTypeIdentifiers\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/UniformTypeIdentifiers-24ECE4SFK7PGSABBMUJE1XMBK.pcm -Xcc -fmodule-file\=UserNotifications\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/UserNotifications-78HIQBH4R1WDV26HB7O3QPY1S.pcm -Xcc -fmodule-file\=_AvailabilityInternal\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_AvailabilityInternal-4D9S8ZGM8ESDTK95M0P4I3KKU.pcm -swift-module-file\=_Builtin_float\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/_Builtin_float.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=_Builtin_float\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_Builtin_float-WP0V5ZVY0TTGAJTV8FX73CH.pcm -Xcc -fmodule-file\=_Builtin_intrinsics\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_Builtin_intrinsics-91XCDUB9U8FNNEY5YHLU4F4F8.pcm -Xcc -fmodule-file\=_Builtin_inttypes\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_Builtin_inttypes-UADW50O59E9Q4VHP1T24R6D5.pcm -Xcc -fmodule-file\=_Builtin_limits\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_Builtin_limits-2PLPURUQEQR1HX946JY5MYO52.pcm -Xcc -fmodule-file\=_Builtin_stdarg\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_Builtin_stdarg-3IZKUMB80JHH4INXGA1OT0XGS.pcm -Xcc -fmodule-file\=_Builtin_stdatomic\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_Builtin_stdatomic-ALZSPAZTS8NGWH09WERRLWUF8.pcm -Xcc -fmodule-file\=_Builtin_stdbool\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_Builtin_stdbool-BVIH1BL1IAES75DDJRBPAJ6TP.pcm -Xcc -fmodule-file\=_Builtin_stddef\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_Builtin_stddef-7XTVMJJWCOOG0TXY8M3SMTBMN.pcm -Xcc -fmodule-file\=_Builtin_stdint\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_Builtin_stdint-1SZHB7BEN5LOWTL286NE4IKNR.pcm -Xcc -fmodule-file\=_Builtin_tgmath\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_Builtin_tgmath-72TPRD4FZEQ0HS0VI2YLF0JWI.pcm -swift-module-file\=_Concurrency\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/_Concurrency.swiftmodule/arm64e-apple-xros.swiftmodule -swift-module-file\=_DarwinFoundation1\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/_DarwinFoundation1.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=_DarwinFoundation1\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_DarwinFoundation1-AACJ9DO8YXPPH9LWKQIB1AZEJ.pcm -swift-module-file\=_DarwinFoundation2\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/_DarwinFoundation2.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=_DarwinFoundation2\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_DarwinFoundation2-1K9RBFQ0JERYFB7IYRC25YJU4.pcm -swift-module-file\=_DarwinFoundation3\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/_DarwinFoundation3.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=_DarwinFoundation3\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_DarwinFoundation3-I9Q8Z6HJ5288M1GE96PK4NOL.pcm -swift-module-file\=_StringProcessing\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/_StringProcessing.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=_SwiftConcurrencyShims\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/_SwiftConcurrencyShims-3ESPSRF1VO3JLMSQR54AVUW65.pcm -swift-module-file\=os\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/os.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=os\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/os-59NWGC33FRCQC9BSF5GY4BNB5.pcm -Xcc -fmodule-file\=os_object\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/os_object-8IS0B4BUQ2S9ADNA5NDFTN0JS.pcm -Xcc -fmodule-file\=os_workgroup\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/os_workgroup-DUV648XE5NMZJWK26O5A48M76.pcm -Xcc -fmodule-file\=ptrauth\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/ptrauth-BZ3KG9IQJEM2YRBIACFSIQ7QO.pcm -Xcc -fmodule-file\=ptrcheck\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/ptrcheck-F3PPRTG0A21LYIN56N63CD4R4.pcm -swift-module-file\=simd\=/Applications/Xcode-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/xros/prebuilt-modules/26.0/simd.swiftmodule/arm64e-apple-xros.swiftmodule -Xcc -fmodule-file\=simd\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/simd-DLQFA7YV5QJLWVYFX3KLW7QWH.pcm -Xcc -fmodule-file\=sys_types\=/Users/<user-folder>/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/sys_types-MEHPPBTRTZVHFILNPOHBOEGN.pcm -o /Users/<user-folder>/Library/Developer/Xcode/DerivedData/SentryTest-flsvjxbwleqdnsaymtsydicicxcg/Build/Intermediates.noindex/SwiftExplicitPrecompiledModules/Sentry-31HNN5GL4VE6H.swiftmodule -load-resolved-plugin /Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/usr/lib/swift/host/plugins/libFoundationMacros.dylib\#/Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/usr/bin/swift-plugin-server\#FoundationMacros -load-resolved-plugin /Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/usr/lib/swift/host/plugins/libObservationMacros.dylib\#/Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/usr/bin/swift-plugin-server\#ObservationMacros -load-resolved-plugin /Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/usr/lib/swift/host/plugins/libPreviewsMacros.dylib\#/Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/usr/bin/swift-plugin-server\#PreviewsMacros -load-resolved-plugin /Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/usr/lib/swift/host/plugins/libSwiftMacros.dylib\#/Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/usr/bin/swift-plugin-server\#SwiftMacros -load-resolved-plugin /Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/usr/lib/swift/host/plugins/libSwiftUIMacros.dylib\#/Applications/Xcode-beta-3.app/Contents/Developer/Platforms/XROS.platform/Developer/usr/bin/swift-plugin-server\#SwiftUIMacros

```

**Comment by philippsuess** [comment]
@levinli303 could you maybe provide us a small sample app for a repro?

**Comment by vedlai** [comment]
@philipphofmann here is a sample

[SentryTest.zip](https://github.com/user-attachments/files/21391048/SentryTest.zip)

**Comment by philippsuess** [comment]
Thanks a lot @vedlai. I can now reproduce the issue with Xcode 26 beta 4 on macOS 15.5 when compiling your sample project for visionOS.

**Comment by vedlai** [comment]
@philipphofmann Is there any update on a fix? Just wondering if I need to go towards a different solution for now.

**Comment by philippsuess** [comment]
No, we don't have an update yet, sorry @vedlai.

**Comment by dougholland** [comment]
I’m also running into this same issue, hopefully the bug fix will be available by the time Xcode 26 is released.

**Comment by vvbutko** [comment]
Same for me. Also hope it's fixed soon.

**Comment by dougholland** [comment]
Please provide an update on this issue as its impacting an upcoming app release and I have had to not only remove Sentry from the visionOS app but also from several shared components used by iOS and iPadOS.

**Comment by itaybre** [comment]
> Please provide an update on this issue as its impacting an upcoming app release and I have had to not only remove Sentry from the visionOS app but also from several shared components used by iOS and iPadOS.

The fix is waiting for the next release here: https://github.com/getsentry/sentry-cocoa/pull/5823

**Comment by dougholland** [comment]
> > Please provide an update on this issue as its impacting an upcoming app release and I have had to not only remove Sentry from the visionOS app but also from several shared components used by iOS and iPadOS.
> 
> The fix is waiting for the next release here: [#5823](https://github.com/getsentry/sentry-cocoa/pull/5823)

Awesome, thank you!  Are you able to provide some idea of the timeframe for the next release?

**Comment by philippsuess** [comment]
@dougholland, either this week or early next week.

**Comment by philprime** [comment]
@dougholland we just released [v8.55.0](https://github.com/getsentry/sentry-cocoa/releases/tag/8.55.0). Could you please take a look if it resolves the issue for you?

**Comment by philippsuess** [comment]
Let's close this. If [v8.55.0](https://github.com/getsentry/sentry-cocoa/releases/tag/8.55.0) doesn't fix the issue, please reopen with more details.

**Comment by vedlai** [comment]
@philipphofmann @philprime the same project I provided earlier does not build in Xcode Beta 4 , Tahoe, same error, I cleaned the derived folder, updated to 8.55.0.

**Comment by dougholland** [comment]
> [@dougholland](https://github.com/dougholland) we just released [v8.55.0](https://github.com/getsentry/sentry-cocoa/releases/tag/8.55.0). Could you please take a look if it resolves the issue for you?

I'll take a look later today although given that @vedlai has said that it does not resolve the issue, it's probably still an issue with the latest beta of Xcode 26 and visionOS 26.

**Comment by Michael-Panic** [comment]
v8.55.0 did not resolve the issue for me either, and I'm on a newer version of the Xcode 26 beta than vedlai. I tried `Sentry-Dynamic-WithARM64e`, `Sentry-Dynamic`, and `sentry.xcframework`. My app typically just uses `sentry.xcframework`.

The problem is very simple to reproduce. It may only happen in the macOS 26 beta.

1. Create a new VisionOS app
2. Add sentry.xcframework to the project
3. `import Sentry` in one of the source code files
4. Build for Vision Pro or simulator

```
<unknown>:0: error: C99 was enabled in PCH file but is currently disabled
<unknown>:0: error: module file /Users/buckley/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/SwiftShims-F0X08FK1JUCENOH04HR213CXU.pcm cannot be loaded due to a configuration mismatch with the current compilation
<unknown>:0: error: missing required module 'SwiftShims'
```

Here's a project you can test. Just drop Sentry.xcframework into `SentryLinking26/SentryLinking26` (in the same folder as `ContentView.swift`), open in Xcode, and build. Github won't allow me to upload the project with sentry.xcframework in it. The file is too large.

[SentryLinking26.zip](https://github.com/user-attachments/files/21781131/SentryLinking26.zip)

Sorry to jump in on this one, but it's been making my life difficult for the last month and a half. Every time I need to test on Vision Pro, I have to temporarily delete the Sentry code, then add it back in before I commit.

**Comment by itaybre** [comment]
The fix was merged yesterday: https://github.com/getsentry/sentry-cocoa/pull/5823
Since the fix is actually on the Package file, if you change the settings in Xcode to use from `main` branch instead of `8.55.0` you will be able to build.
You will still be using `8.55.0` code, but with the updated settings.

The fix will be in a release in 2 weeks.

**Comment by Michael-Panic** [comment]
Thanks for fixing this. I've never been able to get Sentry's xcframework build scripts to work on my machine, otherwise I would have tried to submit a PR to fix this issue weeks ago. But because of that, I can't test from the main branch either, but I'll be happy to have the fix in two weeks.

**Comment by vedlai** [comment]
@itaybre yes main works. Thank you!

**Comment by JagCesar** [comment]
@itaybre I'm still getting this error, both when targeting `main` and `.upToNextMajor(from: "8.0.0")`.

Is this a known issue and is there a known workaround?

**Comment by philprime** [comment]
@JagCesar which version did `.upToNextMajor(from: "8.0.0")` resolve to? When switching to `main`, did you fully clean derived data?

**Comment by vedlai** [comment]
@philprime @itaybre I am also seeing this in another project.

The basic project I shared before works fine with main but an older much larger project does not work and I can't replicate it into something I can share.

Any clues on what the fix was so I can try and replicate?

**Comment by philprime** [comment]
Not really, it seems like there's an edge case in project setup that can cause issues.

I am currently working on https://github.com/getsentry/sentry-cocoa/pull/6026 to get Xcode 26 up and running our CI workflows, maybe this will raise more insights, but the GitHub Runners are causing many issues and it's not straight forward.

I just finished setting up the latest Xcode 26 Beta 7 on my machine and will continue investigations.

**Comment by vedlai** [comment]
[SentryTest.zip](https://github.com/user-attachments/files/22081437/SentryTest.zip)

@philprime  The difference seems to the actual "import Sentry" line.

In the original package I does not import sentry because just adding the package caused the error but now the error exists on import.

I marked the line in the ContentView, just comment/uncomment and build to get or remove the error.

I am using Xcode Beta 7

**Comment by philprime** [comment]
@vedlai I downloaded your sample, opened the Xcode project and was able to build and run without any changes. I am using Xcode 26 Beta 7 on macOS 15.5 (24F74)

<img width="1754" height="1007" alt="Image" src="https://github.com/user-attachments/assets/40beee5c-6362-4da5-8cf1-8e21035fd5c1" />

**Comment by vedlai** [comment]
@philprime I am on the latest Tahoe, just downloaded the zip here and tried again.

It is still reproducible on my end by adding and removing "import Sentry" line 10 in the ContentView

Also build for visionOS, the other platforms don't have an issue.

**Comment by itaybre** [comment]
Since Sentry target requires C++ interoperability mode, you need to configure that in your project.<br>I was able to build on Xcode 26 and Tahoe when enabling this flag, set `SWIFT_OBJC_INTEROP_MODE` to `C++ / Objective-C++` in Xcode and you will be able to build without issues.

<img src="https://uploads.linear.app/3ed206af-f87a-40aa-82a0-150bf83e43e6/f9c1cbd4-7299-456a-801d-35613f9ce70f/3e0cac50-c2d9-4e97-8b3e-2ae819a84af1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzNlZDIwNmFmLWY4N2EtNDBhYS04MmEwLTE1MGJmODNlNDNlNi9mOWMxY2JkNC03Mjk5LTQ1NmEtODAxZC0zNTYxM2Y5Y2U3MGYvM2UwY2FjNTAtYzJkOS00ZTk3LThiM2UtMmFlODE5YTg0YWYxIiwiaWF0IjoxNzU2ODM3MzE3LCJleHAiOjMzMzI3Mzk3MzE3fQ._-DEy8qEzvw-3a-sew9sskZYry-8-VHsP2ZdcFP_Z7E " alt="image.png" width="524" data-linear-height="161" />

**Comment by vedlai** [comment]
@itaybre ok that works for an Xcode project but what about an SPM package?

I usually load sentry from a local package (reusability) into my project and that is failing now.

````
import PackageDescription

let package = Package(
    name: "SentryTestPackage",
    platforms: [
        .visionOS(.v1),
        ],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "SentryTestPackage",
            targets: ["SentryTestPackage"]
        ),
        
    ],
    dependencies: [
        .package(url: "https://github.com/getsentry/sentry-cocoa.git", branch: "main")
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "SentryTestPackage", dependencies: [
                .product(name: "SentrySwiftUI", package: "sentry-cocoa")

            ]
        ),
        
        .testTarget(
            name: "SentryTestPackageTests",
            dependencies: ["SentryTestPackage"]
        ),
    ],
    
)
````

Just that and `import Sentry` anywhere in the package. 

When added to the project it will fail with the same error.

Is there a way to add interoperability to a package?

**Comment by itaybre** [comment]
You should be able to add the swift settings to the target:

```
swiftSettings: [
    .interoperabilityMode(.Cxx, .when(platforms: [.visionOS]))
]
```

**Comment by vedlai** [comment]
@itaybre That seems to work, I will finish up the integration later but it is building right now.

Thank you so much! Y'all are an awesome team.

**Comment by philippsuess** [comment]
@itaybre will update the docs with the fix and then we can close this.

**Comment by Michael-Panic** [comment]
Switching the interoperability from the default to `C++ / Objective C++` is causing a lot of errors for my project, which is strange, because I'm already using C++ and Objective-C++, and it was all working without changing the interoperability setting.

**Comment by Michael-Panic** [comment]
OK, apologies upfront, but could I ask you to remove the C++/Objective-C++ interoperability setting from Sentry on VisionOS instead? There are a few reasons I'm asking this.

1. It doesn't actually seem to be necessary. I may be mistaken about this, but if I clone the repo, remove the setting from SDK.xcconfig, and build for VisionOS in Xcode, Sentry.framework compiles without issue.

2. Enabling C++/Objective-C++ interoperability actually changes the compiler behavior in a way that's incompatible with some third-party open-source C libraries I'm dependent on. In particular, these are C libraries that add `extern "C"` blocks in their headers when being compiled with a C++ compiler, but Swift's C++ interoperability adds extra requirements to imports within `extern "C"` blocks. E.g. if one of these libraries attempts to include the C header for stdint, (`#include <stdint.h`), the compiler produces an error `Import of C++ module 'std_stdint_h' appears within extern "C" language linkage specification`.

3. The requirement only applies to VisionOS currently, but my code is for a cross-platform app. And there are some code changes necessary when adopting C++ interoperability, so either I need to add a lot of #if/#elses to my code, or I have to enable C++ interoperability to my app on all platforms, which will require more work to make third-party dependencies on other platforms work with it.

**Comment by JagCesar** [comment]
> Since Sentry target requires C++ interoperability mode, you need to configure that in your project.I was able to build on Xcode 26 and Tahoe when enabling this flag, set `SWIFT_OBJC_INTEROP_MODE` to `C++ / Objective-C++` in Xcode and you will be able to build without issues.
> 
> <img alt="image.png" width="524" src="https://camo.githubusercontent.com/7bd04f2a7360285e6799ca0ad454eb288025f485a88fd9f4235b1758fefacabf/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f33656432303661662d663837612d343061612d383261302d3135306266383365343365362f66396331636264342d373239392d343536612d383031642d3335363133663963653730662f33653063616335302d633264392d346539372d386233652d3261653831396138346166313f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a4e6c5a4449774e6d466d4c5759344e3245744e444268595330344d6d45774c5445314d474a6d4f444e6c4e444e6c4e69396d4f574d7859324a6b4e4330334d6a6b354c5451314e6d45744f4441785a43307a4e5459784d325935593255334d4759764d3255775932466a4e544174597a4a6b4f5330305a546b334c5468694d3255744d6d466c4f44453559546730595759784969776961574630496a6f784e7a55324f444d334d7a45334c434a6c654841694f6a4d7a4d7a49334d7a6b334d7a453366512e5f2d4445793871457a76772d33612d7365773973736b5a5972792d382d56487350325a646346505f5a374520">

I agree with what @Michael-Panic is asking for above, but for other reasons.

I don't think it's reasonable to require developers to change `SWIFT_OBJC_INTEROP_MODE` to use Sentry. Sentry should be a plug-and-play solution with minimal config, in my opinion. This is one of the reasons I prefer Sentry over other alternatives.

**Comment by itaybre** [comment]
@Michael-Panic @vedlai @JagCesar you were right and thanks for the push back on this fix.
Because of this we noticed the issue underneath and fixed it here: https://github.com/getsentry/sentry-cocoa/pull/6077

Now there is no need to use the interop flag, and just integrate visionOS

**Comment by JagCesar** [comment]
I tried building our project with the latest commit on `main` and am still getting this error. 

<img width="941" height="318" alt="Image" src="https://github.com/user-attachments/assets/79f8d8c7-d171-4e16-87d8-42fcadd6fb28" />

Here's a screenshot off our lock file, proof that we're really building with HEAD of `main`

<img width="551" height="182" alt="Image" src="https://github.com/user-attachments/assets/1b4035d1-30aa-4268-83e7-e657290514a1" />

We're compiling on Xcode Cloud with the latest release of macOS and the latest beta of Xcode.

**Comment by vedlai** [comment]
@itaybre Thank you for all your work.

It doesn't seem to be working with or without the flags now, it was working fine with the flags earlier today.

**Comment by levinli303** [comment]
it seems Sentry pulls pre-built framework from release for SPM, so we still need to wait for them to make a new release.

**Comment by itaybre** [comment]
> it seems Sentry pulls pre-built framework from release for SPM, so we still need to wait for them to make a new release.

You are right, right now SPM uses a prebuilt framework. But we released [`8.56.0-alpha.1`](https://github.com/getsentry/sentry-cocoa/releases/tag/8.56.0-alpha.1) which should let you build on Xcode 26.

We are working to enable building from source, but that's an ongoing process.

**Comment by levinli303** [comment]
I can confirm with https://github.com/getsentry/sentry-cocoa/commit/5c2d5d6c64f9492d2912963f04f0b039f72993d4 I can build my project successfully.

**Comment by vedlai** [comment]
My projects builds but Sentry causes a crash when opening a menu in an ornament.

This did not happen with the flags enabled version of Sentry and only happens when I have Sentry in my project.

<img width="1060" height="230" alt="Image" src="https://github.com/user-attachments/assets/ddf35a7e-f6f6-446d-b9c5-76228399c314" />

I have to move on from Sentry for now since I have to get my apps and my client's apps out, I'll try and recreate a project where it happens after I get everything out.

**Comment by philprime** [comment]
Looping @noahsmartin in here because I believe the crash is unrelated to iOS 26.0 but instead caused by https://github.com/getsentry/sentry-cocoa/pull/6072. It seems like the protocol approach did not work correctly.

**Comment by edgariscoding** [comment]
Is this issue resolved? I get the same error when building for visionOS on Xcode 26 RC and Tahoe RC using Sentry `8.55.1`.

```
C99 was enabled in PCH file but is currently disabled

module file [my-dir]/Xcode/DerivedData/ModuleCache.noindex/SwiftShims-1VIPCI9266QTFHCU040GOH2D7.pcm cannot be loaded due to a configuration mismatch with the current compilation

missing required module ‘SwiftShims’
```

**Comment by itaybre** [comment]
> Is this issue resolved? I get the same error when building for visionOS on Xcode 26 RC and Tahoe RC using Sentry `8.55.1`.
> 
> ```
> C99 was enabled in PCH file but is currently disabled
> 
> module file [my-dir]/Xcode/DerivedData/ModuleCache.noindex/SwiftShims-1VIPCI9266QTFHCU040GOH2D7.pcm cannot be loaded due to a configuration mismatch with the current compilation
> 
> missing required module ‘SwiftShims’
> ```

Please use version [8.56.0-alpha.1](https://github.com/getsentry/sentry-cocoa/releases/tag/8.56.0-alpha.1)

**Comment by JagCesar** [comment]
> Is this issue resolved? I get the same error when building for visionOS on Xcode 26 RC and Tahoe RC using Sentry `8.55.1`.
> 
> ```
> C99 was enabled in PCH file but is currently disabled
> 
> module file [my-dir]/Xcode/DerivedData/ModuleCache.noindex/SwiftShims-1VIPCI9266QTFHCU040GOH2D7.pcm cannot be loaded due to a configuration mismatch with the current compilation
> 
> missing required module ‘SwiftShims’
> ```

Yeah I can confirm it's been solved. We're targeting the HEAD of main, building on Xcode Xcloud using latest stable macOS and Xcode RC.

We're building to all apple platforms.

**Comment by edgariscoding** [comment]
> > Is this issue resolved? I get the same error when building for visionOS on Xcode 26 RC and Tahoe RC using Sentry `8.55.1`.
> > 
> > ```
> > C99 was enabled in PCH file but is currently disabled
> > 
> > module file [my-dir]/Xcode/DerivedData/ModuleCache.noindex/SwiftShims-1VIPCI9266QTFHCU040GOH2D7.pcm cannot be loaded due to a configuration mismatch with the current compilation
> > 
> > missing required module ‘SwiftShims’
> > ```
> 
> Please use version [8.56.0-alpha.1](https://github.com/getsentry/sentry-cocoa/releases/tag/8.56.0-alpha.1)

Using the alpha version fixed the issue, thanks

**Comment by philprime** [comment]
Thank you all for the update!<br>We are working on release 8.56.0-alpha.2 right now with a couple of other xOS 26.0 fixes and will try to get out a non-alpha release soon.

**Comment by vedlai** [comment]
@philprime the crash I mentioned before (ProcessInfo) does not seem to be present in alpha2. Thank you!

**Comment by philprime** [comment]
Thank you @vedlai for the update! [v8.56.0](https://github.com/getsentry/sentry-cocoa/releases/tag/8.56.0) is now released as a non-alpha, so feel free to update to that one.
