### ISSUE TITLE
SwiftUI apps stack trace is redacted and useless.

### ISSUE THREAD

**Issue by anonrig** [getsentry/sentry-cocoa#847]
_Platform:_
- [x]  iOS
- [x]  tvOS
- [ ]  MacOS
- [x]  watchOS

_Swift:_
- [x]  Yes -> 5.3
- [ ]  No

_sentry-cocoa installed with:_
- [x] Swift Package Manager
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**6.0.6**

---
I have following issue:

Stack trace is redacted on SwiftUI based app.

**Steps to reproduce:**
- Try throwing an error on SwiftUI based app.

**Actual result:**
<img width="942" alt="Screen Shot 2020-11-11 at 8 33 17 PM" src="https://user-images.githubusercontent.com/1935246/98844447-5fa2df00-245d-11eb-96fa-6c7f42d8f2d4.png">

All of the issues are same on Sentry.

<img width="1276" alt="Screen Shot 2020-11-11 at 8 35 17 PM" src="https://user-images.githubusercontent.com/1935246/98844508-75180900-245d-11eb-9ce8-4374089e294c.png">

**Comment by philipphofmann** [comment]
Thanks, @anonrig for reporting the issue. We just fixed two important bugs with 6.0.9 that could solve parts of this issue. It would help us a lot if you could update and let us know. In the meantime, we are still looking further into this issue.

**Comment by anonrig** [comment]
Thank you for the reply. I'll send an update to AppStore with the change of 6.0.9, and update you on the progress.

**Comment by anonrig** [comment]
hey @philipphofmann, it seems that the issue has been partially solved.

**Comment by philipphofmann** [comment]
@anonrig I'm happy to hear that. What do mean by partially? Which problems do you still encounter?

**Comment by philipphofmann** [comment]
I'm going to close this as we didn't hear anything for over 3 months. Feel free to pen this again @anonrig.
