### ISSUE TITLE
DSYM symbolication fails on SwiftUI apps

### ISSUE THREAD

**Issue by anonrig** [getsentry/sentry-cocoa#848]
_Platform:_
- [x]  iOS
- [x]  tvOS
- [ ]  MacOS
- [x]  watchOS

_Swift:_
- [x]  Yes -> 5.3
- [ ]  No

_sentry-cocoa installed with:_
- [x] Swift Package Manager
- [ ] CocoaPods
- [ ] Carthage
- [ ] Manually

Version of sentry-cocoa:
**6.0.6**

---
I have following issue:

Symbolication of several native libraries are missing even though the actual application symbolication is successful. How's this even possible? Is this a UI bug, or an actual bug on Sentry?

<img width="941" alt="Screen Shot 2020-11-11 at 8 38 42 PM" src="https://user-images.githubusercontent.com/1935246/98844909-0e471f80-245e-11eb-9710-21fd1db7629d.png">

**Comment by philipphofmann** [comment]
Thanks, @anonrig for reporting this. We are looking into this issue and we are going to come back to you with more information.

**Comment by philipphofmann** [comment]
Hi @anonrig, we fixed the symbolication of several native libraries on our servers yesterday. Can you let us now, if this fixes the issue?

**Comment by anonrig** [comment]
Issue still persists with issue id 2020954637, on project 5422524

<img width="944" alt="Screen Shot 2020-11-13 at 4 57 38 PM" src="https://user-images.githubusercontent.com/1935246/99079704-58044700-25d1-11eb-9290-87be402bcbdc.png">

**Comment by philipphofmann** [comment]
Just to be clear @anonrig, you updated to sentry-cocoa 6.0.9 and the issue still persists right?

**Comment by philipphofmann** [comment]
I'm closing this as we didn't hear anything for over 3 months. Feel free to open this again @anonrig.
